### ISSUE TITLE
Initial Checklist

### ISSUE THREAD

**Issue by switchupcb** [switchupcb/discord-api-spec#5]
Created by @dkasabovn, then refactored. Missing Interaction headings and some topics.

## Checklist

- [ ] **Application Resource**
  - [ ] Application Object 
      - [ ] Application Structure 
      - [ ] Example Application Object 
      - [ ] Application Flags 

- [ ] **Audit Logs Resource**
  - [ ] Audit Logs 
  - [ ] Audit Log Object 
      - [ ] Audit Log Structure 
      - [ ] Example Partial Integration Object 
  - [ ] Audit Log Entry Object 
      - [ ] Audit Log Entry Structure 
      - [ ] Audit Log Events 
      - [ ] Optional Audit Entry Info 
  - [ ] Audit Log Change Object 
      - [ ] Audit Log Change Structure 
      - [ ] Audit Log Change Key 
      - [ ] Example Partial Role Object 

- [ ] **Channels Resource**
  - [ ] Channel Object 
      - [ ] Channel Structure 
      - [ ] Channel Types 
      - [ ] Video Quality Modes 
      - [ ] Example Guild Text Channel 
      - [ ] Example Guild News Channel 
      - [ ] Example Guild Voice Channel 
      - [ ] Example DM Channel 
      - [ ] Example Group DM Channel 
      - [ ] Example Channel Category 
      - [ ] Example Store Channel 
      - [ ] Example Thread Channel 
  - [ ] Message Object 
      - [ ] Message Structure 
      - [ ] Message Types 
      - [ ] Message Activity Structure 
      - [ ] Message Activity Types 
      - [ ] Message Flags 
      - [ ] Example Message 
      - [ ] Example Crossposted Message 
  - [ ] Message Reference Object 
      - [ ] Message Reference Structure 
    - [ ] Message Types 
      - [ ] Crosspost messages 
      - [ ] Channel Follow Add messages 
      - [ ] Pin messages 
      - [ ] Replies 
      - [ ] Thread starter message 
  - [ ] Followed Channel Object 
      - [ ] Followed Channel Structure 
  - [ ] Reaction Object 
      - [ ] Reaction Structure 
  - [ ] Overwrite Object 
      - [ ] Overwrite Structure 
  - [ ] Thread Metadata Object 
      - [ ] Thread Metadata Structure 
  - [ ] Thread Member Object 
      - [ ] Thread Member Structure 
  - [ ] Embed Object 
      - [ ] Embed Structure 
      - [ ] Embed Types 
      - [ ] Embed Thumbnail Structure 
      - [ ] Embed Video Structure 
      - [ ] Embed Image Structure 
      - [ ] Embed Provider Structure 
      - [ ] Embed Author Structure 
      - [ ] Embed Footer Structure 
      - [ ] Embed Field Structure 
      - [ ] Embed Limits 
  - [ ] Attachment Object 
      - [ ] Attachment Structure 
  - [ ] Channel Mention Object 
      - [ ] Channel Mention Structure 
  - [ ] Allowed Mentions Object 
      - [ ] Allowed Mention Types 
      - [ ] Allowed Mentions Structure 
      - [ ] Allowed Mentions Reference 
        - [ ] (Group DM) 
        - [ ] (Guild channel) 
        - [ ] (Thread) 
        - [ ] Limitations 
            - [ ] Response Body 
      - [ ] Response Body 
      - [ ] Response Body 
      - [ ] Response Body 

- [ ] **Emoji Resource**
  - [ ] Emoji Object 
      - [ ] Emoji Structure 
      - [ ] Emoji Example 
      - [ ] Standard Emoji Example 
      - [ ] Custom Emoji Examples 
  
- [ ] **Guild Resource**
  - [ ] Guild Object 
      - [ ] Guild Structure 
      - [ ] Default Message Notification Level 
      - [ ] Explicit Content Filter Level 
      - [ ] MFA Level 
      - [ ] Verification Level 
      - [ ] Guild NSFW Level 
      - [ ] Premium Tier 
      - [ ] System Channel Flags 
      - [ ] Guild Features 
      - [ ] Example Guild 
  - [ ] Unavailable Guild Object 
      - [ ] Example Unavailable Guild 
  - [ ] Guild Preview Object 
      - [ ] Guild Preview Structure 
      - [ ] Example Guild Preview 
  - [ ] Guild Widget Settings Object 
      - [ ] Guild Widget Settings Structure 
      - [ ] Example Guild Widget Settings 
  - [ ] Get Guild Widget Object 
      - [ ] Get Guild Widget Structure 
      - [ ] Example Get Guild Widget 
  - [ ] Guild Member Object 
      - [ ] Guild Member Structure 
      - [ ] Example Guild Member 
  - [ ] Integration Object 
      - [ ] Integration Structure 
      - [ ] Integration Expire Behaviors 
  - [ ] Integration Account Object 
      - [ ] Integration Account Structure 
  - [ ] Integration Application Object 
      - [ ] Integration Application Structure 
  - [ ] Ban Object 
      - [ ] Ban Structure 
      - [ ] Example Ban 
  - [ ] Welcome Screen Object 
      - [ ] Welcome Screen Structure 
      - [ ] Welcome Screen Channel Structure 
      - [ ] Example Welcome Screen 
  - [ ] Membership Screening Object 
      - [ ] Example Partial Channel Object 
      - [ ] Example Category Channel 
      - [ ] Example Response 
      - [ ] Response Body 
              - [ ] Example Partial Invite Object 
      - [ ] Widget Style Options 
      - [ ] Caveats 
      - [ ] Caveats 

- [ ] **Guild Scheduled Event**
  - [ ] Guild Scheduled Event Object 
      - [ ] Guild Scheduled Event Structure 
      - [ ] Guild Scheduled Event Privacy Level 
      - [ ] Guild Scheduled Event Entity Types 
      - [ ] Field Requirements By Entity Type 
      - [ ] Guild Scheduled Event Status 
      - [ ] Valid Guild Scheduled Event Status Transitions 
      - [ ] Guild Scheduled Event Entity Metadata 
  - [ ] Guild Scheduled Event User Object 
      - [ ] Guild Scheduled Event User Structure 
  - [ ] Guild Scheduled Event Status Update Automation 
  - [ ] Guild Scheduled Event Permissions Requirements 

- [ ] **Guild Template Resource**
  - [ ] Guild Template Object 
      - [ ] Guild Template Structure 
      - [ ] Example Guild Template Object 
  
- [ ] **Invite Resource**
  - [ ] Invite Object 
      - [ ] Invite Structure 
      - [ ] Invite Target Types 
      - [ ] Example Invite Object 
  - [ ] Invite Metadata Object 
      - [ ] Invite Metadata Structure 
      - [ ] Example Invite Metadata 
  - [ ] Invite Stage Instance Object 
      - [ ] Invite Stage Instance Structure 
      - [ ] Example Invite Stage Instance 
  
- [ ] **Stage Instance Resource**
  - [ ] Stage Instance Object 
      - [ ] Stage Instance Structure 
      - [ ] Privacy Level 
      - [ ] Example Stage Instance 
  - [ ] Definitions 
  - [ ] Auto Closing 
  
- [ ] **Sticker Resource**
  - [ ] Sticker Object 
      - [ ] Sticker Structure 
      - [ ] Sticker Types 
      - [ ] Sticker Format Types 
      - [ ] Example Sticker 
  - [ ] Sticker Item Object 
      - [ ] Sticker Item Structure 
  - [ ] Sticker Pack Object 
      - [ ] Sticker Pack Structure 
      - [ ] Example Sticker Pack 
        - [ ] Response Structure 
        - [ ] Form Params 
  
- [ ] **Users Resource**
  - [ ] Usernames and Nicknames 
  - [ ] User Object 
      - [ ] User Structure 
      - [ ] Example User 
      - [ ] User Flags 
      - [ ] Premium Types 
  - [ ] Connection Object 
      - [ ] Connection Structure 
      - [ ] Visibility Types 
      - [ ] Example Partial Guild 
  
- [ ] **Voice Resource**
  - [ ] Voice State Object 
      - [ ] Voice State Structure 
      - [ ] Example Voice State 
  - [ ] Voice Region Object 
      - [ ] Voice Region Structure 
  
- [ ] **Webhook Resource**
  - [ ] Webhook Object 
      - [ ] Webhook Structure 
      - [ ] Webhook Types 
      - [ ] Example Incoming Webhook 
      - [ ] Example Channel Follower Webhook 
      - [ ] Example Application Webhook

**Comment by switchupcb** [comment]
This isn't sustainable: https://github.com/switchupcb/discord-api-spec/discussions/4
